server:
  port: 8083
  
spring:
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
    api-test:
      path: /api-test/**
      serviceId: test-service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000